version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - fatcontext
    - forcetypeassert
    - goconst
    - gosec
    - govet
    - ineffassign
    - makezero
    - modernize
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      max-open-files: 2048
      confidence: 0.8
      severity: warning
      enable-all-rules: false
      rules:
        - name: context-as-argument # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
          severity: warning
          disabled: false
        - name: defer # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#defer
          severity: warning
          disabled: false
        - name: unexported-return # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
          severity: warning
          disabled: false
        - name: exported # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: false
    usetesting:
      context-background: true
      context-todo: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
          - goconst
        path: (.+)_test\.go

      - linters:
          - revive
        path: synthesize/voice.go
        text: "exported const .* should have comment"
formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/occamist/laverna)
      custom-order: true
